---
- name: Set distribution family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure variables are set correctly.
  include_tasks: variable-check.yml

- name: Install required packages.
  package:
    name: "{{ sysctl_required_packages }}"
    state: present

- name: Ensure the /etc/sysctl.d/ directory exists.
  file:
    path: /etc/sysctl.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Apply configuration.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set | default(sysctl_set) }}"
    reload: "{{ item.reload | default(sysctl_reload) }}"
    state: "{{ item.state | default('present') }}"
    sysctl_file: "{{ sysctl_file }}"
  with_items: "{{ sysctl_entries }}"
  when:
    - sysctl_entries is defined
    - item.name is defined
    - item.value is defined
    - ansible_connection != "docker"
    - ansible_connection != "podman"
    - ansible_connection != "container"
  loop_control:
    label: "{{ item.name }} = {{ item.value }}"
