---
- name: Ensure that the variable 'sysctl_set' is set correctly.
  assert:
    that:
      - sysctl_set | type_debug == "bool"
    fail_msg: "'sysctl_set' can be either 'true' or 'false'."

- name: Ensure that the variable 'sysctl_reload' is set correctly.
  assert:
    that:
      - sysctl_reload | type_debug == "bool"
    fail_msg: "'sysctl_reload' can be either 'true' or 'false'."

- name: Ensure that 'state' is either 'present' or 'absent'.
  assert:
    that:
      - item.state == "present" or item.state == "absent"
    fail_msg: "'state' can be either 'present' or 'absent'"
  when:
    - sysctl_entries is defined
    - item.state is defined
  with_items: "{{ sysctl_entries }}"
