---
- name: Converge
  hosts: all

  vars:
    sysctl_entries:
      - name: net.ipv4.ip_forward
        value: 1

      - name: kernel.kptr_restrict
        value: 1
        state: absent
        sysctl_set: false
        reload: true
  tasks:
    - name: "Include sysctl"
      ansible.builtin.include_role:
        name: "ansible-role-sysctl"
